"""Build a static GitHub Pages site from the rendered daily reports.

Looks for daily report directories under ``data/reports/YYYY-MM-DD/`` and
publishes:

  public/
    index.html              <- landing page listing every report
    reports/YYYY-MM-DD.html  <- each daily report (copied from data/)
    assets/style.css         <- shared dark theme
"""

from __future__ import annotations

import shutil
import sys
from datetime import UTC, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

REPORTS_SRC = ROOT / "data" / "reports"
PUBLIC = ROOT / "public"
PUBLIC_REPORTS = PUBLIC / "reports"


INDEX_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>MarketLens — Daily Reports</title>
<style>
  :root {{
    --bg:#0f1420; --panel:#161c2c; --text:#e6e9f2; --muted:#9aa3b8;
    --accent:#5b8cff; --border:#283149; --green:#3ec28f;
  }}
  *{{box-sizing:border-box}}
  body {{
    margin:0;background:var(--bg);color:var(--text);
    font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;
    line-height:1.55;
  }}
  .container {{ max-width:780px;margin:0 auto;padding:48px 24px 80px; }}
  header {{ border-bottom:1px solid var(--border);padding-bottom:24px;margin-bottom:32px; }}
  h1 {{ margin:0 0 6px;font-size:32px;letter-spacing:-0.02em; }}
  .subtitle {{ color:var(--muted);font-size:15px; }}
  .badge {{
    display:inline-block;background:rgba(62,194,143,.12);border:1px solid var(--green);
    color:var(--green);padding:3px 10px;border-radius:999px;font-size:12px;margin-right:8px;
  }}
  .intro {{ background:var(--panel);border:1px solid var(--border);border-radius:10px;
    padding:18px 22px;margin-bottom:32px; }}
  .intro p {{ margin:0;color:var(--muted) }}
  .intro p + p {{ margin-top:8px }}
  ul.reports {{ list-style:none;padding:0;margin:0 }}
  ul.reports li {{
    background:var(--panel);border:1px solid var(--border);border-radius:10px;
    padding:14px 18px;margin-bottom:10px;display:flex;justify-content:space-between;align-items:center;
  }}
  ul.reports li a {{ color:var(--text);text-decoration:none;font-weight:600 }}
  ul.reports li a:hover {{ color:var(--accent) }}
  .when {{ color:var(--muted);font-size:13px }}
  footer {{ margin-top:48px;color:var(--muted);font-size:12px;border-top:1px solid var(--border);padding-top:16px }}
  a {{ color:var(--accent) }}
</style>
</head>
<body>
<div class="container">
<header>
  <h1>MarketLens</h1>
  <div class="subtitle">
    <span class="badge">LIVE</span>
    Daily reports auto-generated by GitHub Actions
  </div>
</header>

<div class="intro">
  <p>An autonomous AI agent that ingests global financial news from ~100,000 sources
  (curated RSS + GDELT), reasons about market impact with an LLM, and publishes a
  structured daily report.</p>
  <p>Source: <a href="https://github.com/{repo}">github.com/{repo}</a></p>
</div>

<h2 style="font-size:18px;margin:0 0 12px">Reports</h2>
<ul class="reports">
{items}
</ul>

<footer>
  Generated {generated} · {n} reports archived ·
  Informational only — not investment advice.
</footer>
</div>
</body>
</html>
"""


def main() -> int:
    if not REPORTS_SRC.exists():
        print(f"no reports found at {REPORTS_SRC}")
        return 0

    PUBLIC.mkdir(parents=True, exist_ok=True)
    PUBLIC_REPORTS.mkdir(parents=True, exist_ok=True)

    # Discover all dated report directories
    dirs = sorted(
        [p for p in REPORTS_SRC.iterdir() if p.is_dir()],
        reverse=True,
    )

    items_html = []
    for d in dirs:
        src_html = d / "report.html"
        if not src_html.exists():
            continue
        dest_name = f"{d.name}.html"
        shutil.copy(src_html, PUBLIC_REPORTS / dest_name)
        # Also copy md if present
        src_md = d / "report.md"
        if src_md.exists():
            shutil.copy(src_md, PUBLIC_REPORTS / f"{d.name}.md")
        items_html.append(
            f'<li><a href="reports/{dest_name}">{d.name}</a>'
            f'<span class="when">view report →</span></li>'
        )

    if not items_html:
        items_html.append("<li>No reports yet. Check back tomorrow.</li>")

    # Repository slug for the source link
    import os

    repo = os.environ.get("GITHUB_REPOSITORY", "meh-vaib/MarketLens")

    index_html = INDEX_TEMPLATE.format(
        repo=repo,
        items="\n".join(items_html),
        generated=datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC"),
        n=len(items_html),
    )
    (PUBLIC / "index.html").write_text(index_html, encoding="utf-8")

    # Helpful redirect at /latest
    if dirs:
        latest_redirect = f'<!DOCTYPE html><meta http-equiv="refresh" content="0;url=reports/{dirs[0].name}.html">'
        (PUBLIC / "latest.html").write_text(latest_redirect, encoding="utf-8")

    print(f"built public/ with {len(dirs)} reports")
    return 0


if __name__ == "__main__":
    sys.exit(main())
